# Generated by Django 5.1.3 on 2024-11-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pretixbase",
            "0004_alter_cachedcombinedticket_id_alter_cachedticket_id_and_more",
        ),
        ("stripe2", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedstripeobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="referencedstripeobject",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe2_order_references",
                to="pretixbase.order",
            ),
        ),
        migrations.AlterField(
            model_name="referencedstripeobject",
            name="payment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe2_payment_references",
                to="pretixbase.orderpayment",
            ),
        ),
        migrations.AlterField(
            model_name="registeredapplepaydomain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
