# Generated by Django 5.1.3 on 2024-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedstripeobject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="registeredapplepaydomain",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
